config/routes.rb
# rubocop:disable Lint/MissingCopEnableDirective, Metrics/BlockLength
Rails.application.routes.draw do
  draw(:redirects)
  ActiveAdmin.routes(self)

  require 'sidekiq/web'
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  if Rails.env.development?
    mount Lookbook::Engine, at: '/lookbook'
  end

  resource :github_webhooks, only: :create, defaults: { formats: :json }

  unauthenticated do
    root 'static_pages#home'
  end

  authenticated :user do
    root to: redirect('/dashboard'), as: :authenticated_root
  end

  devise_for(
    :users,
    module: 'users',
    controllers: { passwords: 'users/password_resets' },
    path_names: { password: 'password_reset' }
  )

  devise_scope :user do
    get '/sign_in' => 'users/sessions#new'
    get '/sign_out' => 'users/sessions#destroy', method: :delete
    get '/sign_up' => 'users/registrations#new'
  end

  namespace :api do
    resources :lesson_completions, only: [:index]
    resources :points, only: %i[index show create]
  end

  get 'home' => 'static_pages#home'
  get 'about' => 'static_pages#about'
  get 'faq' => 'static_pages#faq'
  get 'contributing' => 'static_pages#contributing'
  get 'terms_of_use' => 'static_pages#terms_of_use'
  get 'success_stories' => 'static_pages#success_stories'
  get 'community_rules' => 'static_pages#community_rules'
  get 'community_expectations' => 'static_pages#community_expectations'
  get 'before_asking' => 'static_pages#before_asking'
  get 'how_to_ask' => 'static_pages#how_to_ask'
  get 'sitemap' => 'sitemap#index', defaults: { format: 'xml' }

  # failure route if github information returns invalid
  get '/auth/failure' => 'omniauth_callbacks#failure'
  get 'dashboard' => 'users#show', as: :dashboard

  namespace :users do
    resources :paths, only: :create
    resources :progress, only: :destroy
    resource :profile, only: %i[edit update]
  end

  namespace :lessons do
    resource :preview, only: %i[show create] do
      post :markdown
    end
    resources :installation_lessons, only: %i[index]
  end

  namespace :courses do
    resources :progress, only: %i[show]
  end

  resources :lessons, only: :show do
    resources :project_submissions, only: %i[index], controller: 'lessons/project_submissions'

    resources :lesson_completions, only: %i[create], as: 'completions'
    delete 'lesson_completions' => 'lesson_completions#destroy', as: 'lesson_completions'
  end

  resources :project_submissions do
    resources :flags, only: %i[create], controller: 'project_submissions/flags'
    resources :likes, controller: 'project_submissions/likes'
  end

  resources :paths, only: %i[index show] do
    resources :courses, only: :show
  end

  resources :notifications, only: %i[index update]
  resource :themes, only: :update

  match '/404' => 'errors#not_found', via: %i[get post patch delete]
end

app/views/shared/_bottom_cta.html.erb
<div class="py-20 text-center max-w-4xl mx-auto">
  <h4 class="text-2xl mb-4 font-light leading-10 text-gray-600 dark:text-gray-200"><%= heading %></h4>
  <p class="font-normal mb-10 text-gray-500 dark:text-gray-400"><%= sub_heading %></p>
  <%= button %>
</div>

app/views/shared/_flash.html.erb
<div class="flex flex-col items-end space-y-4">
  <div class="fixed top-10 z-40 mr-8">
    <% flash.each do |type, message| %>
      <%= render Alerts::FlashComponent.new(type:, message:) %>
    <% end %>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer class="bg-white dark:bg-gray-800">
  <div class="max-w-7xl px-4 sm:px-6 lg:px-8 py-3 mx-auto">
    <div class="flex justify-center lg:justify-between py-8">
      <div class="w-80">
        <div class='flex-shrink-0 hidden lg:block items-center'>
          <%= render LogoComponent.new(classes: 'block h-15 w-auto') %>
        </div>

        <p class="py-8 hidden lg:block text-gray-500 dark:text-gray-400">High quality coding education created by an Open-Source community.</p>

        <div class="flex justify-between">
          <%= link_to 'https://github.com/TheOdinProject' do %>
            <span aria-label="github" class="text-gray-700 dark:text-gray-300 hover:text-gray-800 dark:hover:text-gray-400 text-4xl fab fa-github" />
          <% end %>

          <%= link_to 'https://discord.gg/V75WSQG' do %>
            <span aria-label="discord chat" class="text-gray-700 dark:text-gray-300 hover:text-gray-800 dark:hover:text-gray-400 text-4xl fab fa-discord" />
          <% end %>

          <%= link_to 'https://www.facebook.com/theodinproject/' do %>
            <span aria-label="facebook" class="text-gray-700 dark:text-gray-300 hover:text-gray-800 dark:hover:text-gray-400 text-4xl fab fa-facebook" />
          <% end %>

          <%= link_to 'https://twitter.com/TheOdinProject' do %>
            <span aria-label="twitter" class="text-gray-700 dark:text-gray-300 hover:text-gray-800 dark:hover:text-gray-400 text-4xl fab fa-twitter" />
          <% end %>
        </div>
      </div>

      <%= render 'shared/footer_cta' %>
    </div>

    <div class="flex lg:flex-row items-center justify-center lg:justify-start lg:pb-4 gap-y-6 pt-6">
      <div class="flex items-center space-x-0 gap-x-8 gap-y-3 flex-wrap justify-center md:block md:space-x-10">
        <%= link_to 'About', about_path, class: 'hover:text-gray-500 dark:hover:text-gray-400' %>
        <%= link_to 'FAQ', faq_path, class: 'hover:text-gray-500 dark:hover:text-gray-400', data: { test_id: 'faq-link' } %>
        <%= link_to 'Blog', ODIN_BLOG_URL, target: '_blank', rel: 'noreferrer', class: 'hover:text-gray-500 dark:hover:text-gray-400' %>
        <%= link_to 'Success Stories', success_stories_path, class: 'hover:text-gray-500 dark:hover:text-gray-400' %>
        <%= link_to 'Contribute', contributing_path, class: 'hover:text-gray-500 dark:hover:text-gray-400' %>
        <%= link_to 'Appendix', lessons_installation_lessons_path, class: 'hover:text-gray-500 dark:hover:text-gray-400' %>
        <%= link_to 'Terms of Use', terms_of_use_path, class: 'hover:text-gray-500 dark:hover:text-gray-400' %>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_footer_cta.html.erb
<% if user_signed_in? %>
  <div class="rounded-md p-8 hidden lg:block">
    <h3 class="text-3xl font-bold text-gray-700 dark:text-gray-200">Have a question?</h2>
    <p class="py-3 text-gray-500 dark:text-gray-400 text-md w-96">Chat with the Odin community on Discord!</p>

    <%= link_to ODIN_CHAT_URL, class: 'button button--dark text-base px-14' do %>
      Open Discord
    <% end %>
  </div>
<% else %>
  <div class="px-8 pt-2 bg-white dark:bg-gray-800 hidden lg:flex flex-col justify-center">
    <h3 class="text-2xl font-semibold pb-6">Start learning for free</h3>

    <%= form_with url: sign_up_path, method: :get do |form| %>
      <div class="dark-form-input p-1 flex rounded-md bg-white dark:bg-gray-800 focus-within:ring-2 focus-within:ring-indigo-500 dark:focus-within:ring-gray-500 border border-gray-300 dark:border-gray-500">
        <%= form.email_field :email, placeholder: 'Email Address', required: true, class: 'bg-white border-none dark:bg-gray-800 dark:placeholder-gray-400 focus:ring-0 w-60 p-2 focus:outline-none block rounded-none lg:w-80 lg:text-md rounded-l-md' %>
        <%= form.submit 'Get Started!', class: 'button button--primary py-2' %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/shared/_ga.html.erb
<!-- Google Analytics Tracking Snippet -->
<!-- Only load it if we're in a production environment! -->

<% if Rails.env.production? %>

  <script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-41005438-1']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
  </script>

<% else %>

  <script type="text/javascript">
    var _gaq = [];
  </script>

<% end %>

app/views/shared/_navbar.html.erb
<%= render 'shared/off_canvas_menu' %>
<nav class="border-gray-200 bg-white dark:bg-gray-900 dark:border-gray-800 <%= 'border-b' unless @landing_page %>">
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-2">
    <div class="flex justify-between">
      <div class="flex">
        <div class="flex-shrink-0 flex items-center">
          <%= link_to root_path, class: 'logo' do %>
            <%= image_tag 'icons/odin-icon.svg', alt: 'Odin Logo', class: 'block lg:hidden h-12 w-auto' %>
          <% end %>

          <%= render LogoComponent.new(classes: 'hidden lg:block h-12 w-auto') %>
        </div>

      </div>
      <div class="hidden md:ml-6 md:flex sm:items-center">
        <% if user_signed_in? %>
          <div class="hidden sm:ml-6 sm:flex sm:space-x-8">
             <%= render Nav::ItemComponent.new(path: dashboard_path, text: 'Dashboard', test_id: 'nav-dashboard') %>
            <%= render Nav::ItemComponent.new(path: paths_url, text: 'All Paths', test_id: 'nav-all-paths') %>
            <%= render Nav::ItemComponent.new(path: ODIN_CHAT_URL, text: 'Community', test_id: 'nav-community') %>
          </div>

          <%= link_to notifications_path, class: 'ml-3 bg-white dark:bg-gray-900 p-1 rounded-full text-gray-400 dark:text-gray-300 relative hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-gold-500', data: { test_id: 'navbar-notification-icon' } do %>
            <span class="sr-only">View notifications</span>
            <% if unread_notifications?(current_user) %>
                <span data-test-id="unread-notifications" class="absolute top-1 right-0.5 w-2 h-2 rounded-lg bg-gold-500"></span>
              <% end %>
            <%= inline_svg_tag 'icons/bell.svg', class: 'h-6 w-6', aria: true, title: 'Notifications icon' %>
          <% end %>

          <%= render User::ProfileDropdownComponent.new(current_user:) %>
        <% else %>
          <div class="hidden md:ml-6 md:flex sm:space-x-8">
          <%= render Nav::ItemComponent.new(path: paths_url, text: 'All Paths', test_id: 'nav-all-paths') %>
          <%= render Nav::ItemComponent.new(path: about_path, text: 'About', test_id: 'nav-about') %>
          <%= render Nav::ItemComponent.new(path: ODIN_CHAT_URL, text: 'Community', test_id: 'nav-community') %>
          <%= render Nav::ItemComponent.new(path: sign_in_path, text: 'Sign in', test_id: 'nav-sign-in') %>
          <%= link_to 'Get Started', sign_up_path, class: 'button button--primary md:px-2 md:py-2 lg:px-4 text-sm', data: { test_id: 'nav-sign-up' } %>
          <%= turbo_frame_tag 'theme_switcher', class: 'flex items-center justify-center' do %>
            <%= render Theme::SwitcherComponent.new(current_theme:, type: :icon_only) %>
          <% end %>
        </div>

        <% end %>
      </div>

      <div class="-mr-2 flex items-center md:hidden">
        <button type="button" data-controller="custom-events" data-action="custom-events#emit" data-custom-events-event-name-value="openMobileMenu" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 dark:text-gray-300 dark:hover:text-gray-200 dark:hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-gold-500" aria-controls="mobile-menu" aria-expanded="false">
          <span class="sr-only">Open mobile menu</span>
          <%= inline_svg_tag 'icons/ham-burger.svg', class: 'block h-6 w-6', aria: true, title: 'Open mobile menu button' %>
        </button>
      </div>
    </div>
  </div>
</nav>

app/views/shared/_off_canvas_menu.html.erb
<div
  data-controller="mobile-menu"
  data-mobile-menu-target="container"
  data-action="custom-events:openMobileMenu@window->mobile-menu#open"
  class="fixed inset-0 flex z-40 hidden lg:hidden"
  role="dialog"
  aria-modal="true">

  <div
    data-mobile-menu-target="menuOverlay"
    data-action="click->mobile-menu#close"
    class="fixed inset-0 bg-gray-600 bg-opacity-75 dark:bg-black dark:bg-opacity-60 hidden"
    aria-hidden="true"
    data-transition-enter="transition-opacity ease-linear duration-200"
    data-transition-enter-start="transform opacity-0"
    data-transition-enter-end="transform opacity-100"
    data-transition-leave="transition-opacity ease-linear duration-200"
    data-transition-leave-start="transform opacity-100"
    data-transition-leave-end="transform opacity-0">
  </div>

    <div
      data-mobile-menu-target="menu"
      class="relative flex-1 flex flex-col max-w-xs w-full bg-white focus:outline-none hidden dark:bg-gray-800"
      data-transition-enter="transition ease-in-out duration-200 transform"
      data-transition-enter-start="-translate-x-full"
      data-transition-enter-end="translate-x-0"
      data-transition-leave="transition ease-in-out duration-200 transform"
      data-transition-leave-start="translate-x-0"
      data-transition-leave-end="-translate-x-full">

      <div
        data-mobile-menu-target="closeButton"
        class="absolute top-2 right-2 -mr-12 pt-3 hidden"
        data-action="click->mobile-menu#close"
        data-transition-enter="transition ease-in-out duration-200"
        data-transition-enter-start="transform opacity-0"
        data-transition-enter-end="transform opacity-100"
        data-transition-leave="transition ease-in duration-200"
        data-transition-leave-start="transform opacity-100"
        data-transition-leave-end="transform opacity-0">
        <button type="button" class="ml-1 flex items-center justify-center h-10 w-10 rounded-full focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white">
          <span class="sr-only">Close sidebar</span>
          <svg class="h-6 w-6 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>

      <div class="flex-1 h-0 pt-3 pb-4 overflow-y-auto">
        <div class="flex-shrink-0 flex items-center px-4">
          <%= render LogoComponent.new(classes: 'h-12 w-auto') %>
        </div>
        <nav aria-label="Sidebar" class="mt-3">
          <div class="px-2 space-y-1">
            <% if user_signed_in? %>
              <%= render Nav::ItemComponent.new(path: dashboard_path, text: 'Dashboard', test_id: 'nav-dashboard', icon_path: 'icons/home.svg', mobile: true) %>
              <%= render Nav::ItemComponent.new(path: paths_url, text: 'All Paths', test_id: 'nav-all-paths', icon_path: 'icons/map.svg', mobile: true) %>
              <%= render Nav::ItemComponent.new(path: notifications_path, text: 'Notifications', test_id: 'nav-notifications', icon_path: 'icons/bell.svg', mobile: true) %>
              <%= render Nav::ItemComponent.new(path: ODIN_CHAT_URL, text: 'Community', test_id: 'nav-community', icon_path: 'icons/speech-bubbles.svg', mobile: true) %>
            <% else %>
              <%= render Nav::ItemComponent.new(path: root_path, text: 'Home', test_id: 'nav-home', icon_path: 'icons/home.svg', mobile: true) %>
              <%= render Nav::ItemComponent.new(path: paths_url, text: 'All Paths', test_id: 'nav-all-paths', icon_path: 'icons/map.svg', mobile: true) %>
              <%= render Nav::ItemComponent.new(path: about_path, text: 'About', test_id: 'nav-about', icon_path: 'icons/information.svg', mobile: true) %>
              <%= render Nav::ItemComponent.new(path: ODIN_CHAT_URL, text: 'Community', test_id: 'nav-community', icon_path: 'icons/speech-bubbles.svg', mobile: true) %>
            <% end %>
          </div>
          <hr class="border-t border-gray-200 my-4" aria-hidden="true">
          <div class="px-2 space-y-1">
            <% if user_signed_in? %>
              <%= render Nav::ItemComponent.new(path: edit_users_profile_path, text: 'Settings', test_id: 'nav-settings', icon_path: 'icons/gear.svg', mobile: true) %>
               <%= turbo_frame_tag 'theme_switcher_mobile' do %>
                <%= render Theme::SwitcherComponent.new(current_theme:, type: :mobile) %>
              <% end %>
              <%= render Nav::ItemComponent.new(path: sign_out_path, text: 'Sign out', test_id: 'nav-sign-out', icon_path: 'icons/sign-out.svg', mobile: true) %>
            <% else %>
              <%= render Nav::ItemComponent.new(path: sign_up_path, text: 'Get started', test_id: 'nav-sign-up', icon_path: 'icons/rocket.svg', mobile: true) %>
              <%= turbo_frame_tag 'theme_switcher_mobile' do %>
                <%= render Theme::SwitcherComponent.new(current_theme:, type: :mobile) %>
              <% end %>
              <%= render Nav::ItemComponent.new(path: sign_in_path, text: 'Sign in', test_id: 'nav-sign-in', icon_path: 'icons/sign-in.svg', mobile: true) %>
            <% end %>
          </div>
        </nav>
      </div>
    </div>

    <div class="flex-shrink-0 w-14" aria-hidden="true">
      <!-- Force sidebar to shrink to fit close icon -->
    </div>
  </div>
</div>