config/routes.rb
# rubocop:disable Lint/MissingCopEnableDirective, Metrics/BlockLength
Rails.application.routes.draw do
  draw(:redirects)
  ActiveAdmin.routes(self)

  require 'sidekiq/web'
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  if Rails.env.development?
    mount Lookbook::Engine, at: '/lookbook'
  end

  resource :github_webhooks, only: :create, defaults: { formats: :json }

  unauthenticated do
    root 'static_pages#home'
  end

  authenticated :user do
    root to: redirect('/dashboard'), as: :authenticated_root
  end

  devise_for(
    :users,
    module: 'users',
    controllers: { passwords: 'users/password_resets' },
    path_names: { password: 'password_reset' }
  )

  devise_scope :user do
    get '/sign_in' => 'users/sessions#new'
    get '/sign_out' => 'users/sessions#destroy', method: :delete
    get '/sign_up' => 'users/registrations#new'
  end

  namespace :api do
    resources :lesson_completions, only: [:index]
    resources :points, only: %i[index show create]
  end

  get 'home' => 'static_pages#home'
  get 'about' => 'static_pages#about'
  get 'faq' => 'static_pages#faq'
  get 'contributing' => 'static_pages#contributing'
  get 'terms_of_use' => 'static_pages#terms_of_use'
  get 'success_stories' => 'static_pages#success_stories'
  get 'community_rules' => 'static_pages#community_rules'
  get 'community_expectations' => 'static_pages#community_expectations'
  get 'before_asking' => 'static_pages#before_asking'
  get 'how_to_ask' => 'static_pages#how_to_ask'
  get 'sitemap' => 'sitemap#index', defaults: { format: 'xml' }

  # failure route if github information returns invalid
  get '/auth/failure' => 'omniauth_callbacks#failure'
  get 'dashboard' => 'users#show', as: :dashboard

  namespace :users do
    resources :paths, only: :create
    resources :progress, only: :destroy
    resource :profile, only: %i[edit update]
  end

  namespace :lessons do
    resource :preview, only: %i[show create] do
      post :markdown
    end
    resources :installation_lessons, only: %i[index]
  end

  namespace :courses do
    resources :progress, only: %i[show]
  end

  resources :lessons, only: :show do
    resources :project_submissions, only: %i[index], controller: 'lessons/project_submissions'

    resources :lesson_completions, only: %i[create], as: 'completions'
    delete 'lesson_completions' => 'lesson_completions#destroy', as: 'lesson_completions'
  end

  resources :project_submissions do
    resources :flags, only: %i[create], controller: 'project_submissions/flags'
    resources :likes, controller: 'project_submissions/likes'
  end

  resources :paths, only: %i[index show] do
    resources :courses, only: :show
  end

  resources :notifications, only: %i[index update]
  resource :themes, only: :update

  match '/404' => 'errors#not_found', via: %i[get post patch delete]
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  extend FriendlyId

  friendly_id :slug_candidates, use: %i[slugged history finders]

  belongs_to :section
  has_one :course, through: :section
  has_one :path, through: :course
  has_one :content, dependent: :destroy
  has_many :project_submissions, dependent: :destroy
  has_many :lesson_completions, dependent: :destroy
  has_many :completing_users, through: :lesson_completions, source: :user

  scope :most_recent_updated_at, -> { maximum(:updated_at) }
  scope :installation_lessons, -> { where(installation_lesson: true) }

  validates :position, presence: true

  delegate :body, to: :content

  def position_in_section
    section_lessons.where('position <= ?', position).count
  end

  def import_content_from_github
    LessonContentImporter.for(self)
  end

  private

  def section_lessons
    section.lessons
  end

  def slug_candidates
    [
      [course.title, title].uniq,
      [course.path_short_title, course.title, title].uniq,
      [course.path_short_title, course.title, title, SecureRandom.hex(2)].uniq
    ]
  end
end

app/controllers/lessons/installation_lessons_controller.rb
module Lessons
  class InstallationLessonsController < ApplicationController
    def index
      @lessons = Lesson.installation_lessons.sort_by do |lesson|
        [lesson.course.position, lesson.path.position]
      end
    end
  end
end

app/controllers/lessons/previews_controller.rb
module Lessons
  class PreviewsController < ApplicationController
    def show
      @preview = LessonPreview.find_or_initialize_by(id: params[:uuid])
    end

    def create
      preview_link = LessonPreview.new(lesson_preview_params)

      if preview_link.save
        render json: { preview_link: lessons_preview_url(uuid: preview_link.id) }, status: :created
      else
        render json: { errors: preview_link.errors.full_messages }, status: :unprocessable_entity
      end
    end

    def markdown
      if content.present?
        render json: { content: MarkdownConverter.new(params[:content]).as_html }
      else
        render json: { content: '<p>Nothing to preview</p>' }
      end
    end

    private

    def content
      params[:content]
    end

    def lesson_preview_params
      params.permit(:content)
    end
  end
end

app/controllers/lessons/project_submissions_controller.rb
module Lessons
  class ProjectSubmissionsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_lesson
    before_action :check_if_project_submitable

    def index
      @user_submission = user_submission

      @pagy, @project_submissions = pagy(public_project_submissions, items: 15)
    end

    private

    def user_submission
      submission = project_submissions_query.current_user_submission

      ProjectSubmissionSerializer.as_json(submission, current_user) if submission.present?
    end

    def public_project_submissions
      project_submissions_query.public_submissions
    end

    def project_submissions_query
      @project_submissions_query ||= ::LessonProjectSubmissionsQuery.new(lesson: @lesson, current_user:)
    end

    def set_lesson
      @lesson = Lesson.find(params[:lesson_id])
    end

    def check_if_project_submitable
      return if @lesson.accepts_submission?

      redirect_to(
        lesson_url(@lesson),
        alert: 'This project does not accept submissions'
      )
    end
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  def show
    @lesson = decorated_lesson

    if user_signed_in?
      @project_submissions = public_project_submissions
      @user_submission = current_user_submission
    end
  end

  private

  def public_project_submissions
    project_submissions_query.public_submissions.map do |submission|
      ProjectSubmissionSerializer.as_json(submission, current_user) if submission.present?
    end
  end

  def current_user_submission
    submission = project_submissions_query.current_user_submission

    ProjectSubmissionSerializer.as_json(submission, current_user) if submission.present?
  end

  def project_submissions_query
    ::LessonProjectSubmissionsQuery.new(lesson: @lesson, current_user:, limit: 10)
  end

  def decorated_lesson
    LessonDecorator.new(lesson)
  end

  def lesson
    Lesson.find(params[:id])
  end
end

app/helpers/lessons_helper.rb
module LessonsHelper
  def github_edit_url(lesson)
    github_link("curriculum/edit/main#{lesson.github_path}")
  end
end

app/views/lessons/_advert.html.erb
<%= render CardComponent.new do |card| %>
  <% card.header do %>
    <div class="flex justify-between gap-x-16 items-center border-b-2 border-gray-200 pb-6 flex-col space-y-6 md:flex-row md:space-y-0">
      <h2 class="text-2xl text-gray-500 dark:text-gray-300 text-center w-2/3 md:text-left">
        Are you interested in accelerating your web development learning experience?
      </h2>
      <%= link_to 'https://www.thinkful.com/?utm_source=odin&utm_medium=cpc&utm_campaign=odin-homepage&utm_content=web-dev-3-icons', class: 'button button--primary' do %>
        Get started
      <% end %>
    </div>
  <% end %>

  <% card.body(classes: 'flex justify-between flex-col items-center space-y-6 lg:space-y-0 lg:flex-row') do %>
    <a href="https://www.thinkful.com/?utm_source=odin&utm_medium=cpc&utm_campaign=odin-homepage&utm_content=tf-logo" alt="Thinkful" class="text-gray-800 dark:text-gray-300">
      <div class="flex items-center space-x-4">
        <%= image_tag 'advert/thinkful-logo.svg', alt: 'Thinkful Logo', class: 'w-14 h-14' %>
        <h2 class="text-2xl font-bold">Thinkful</h2>
      </div>
    </a>

    <ul class="flex items-center space-y-10 flex-col md:flex-row md:space-y-0 md:space-x-10">
      <li class="flex items-center flex-col">
        <%= image_tag 'advert/icon-calendar.svg', alt: '5-6 months', class: 'h-10' %>
        <p class="font-bold text-gray-800 dark:text-gray-300">5-6 months</p>
      </li>

      <li class="flex items-center flex-col">
        <%= image_tag 'advert/icon-guarantee.svg', alt: 'Job Guarantee', class: 'h-10' %>
        <p class="font-bold text-gray-800 dark:text-gray-300">Job Guarantee</p>
      </li>

      <li class="flex items-center flex-col">
        <%= image_tag 'advert/icon-mentor.svg', alt: '1-on-1 Mentorship', class: 'h-10' %>
        <p class="font-bold text-gray-800 dark:text-gray-300">1-on-1 Mentorship</p>
      </li>
    </ul>
  <% end %>
<% end %>

app/views/lessons/_header.html.erb
<header class="mb-16 grid grid-cols-12">
  <div class="flex space-y-4 items-center flex-col col-span-full justify-center xl:space-y-0 xl:space-x-4 xl:flex-row xl:justify-start xl:col-start-2">
    <%= render Progress::BadgeComponent.new(
          course: lesson.course,
          current_user:,
          url: courses_progress_path(lesson.course.id)
        ) %>

    <div class="text-center xl:text-left">
      <h1 class="text-2xl font-semibold capitalize text-gray-800 dark:text-gray-200 min-w-full" data-test-id="lesson-title-header">
        <%= lesson.title %>
      </h1>

      <%= link_to path_course_url(lesson.course.path, lesson.course), class: 'no-underline' do %>
        <h2 class="min-w-full text-lg text-gray-500 dark:text-gray-400" data-test-id="course-title-header">
          <%= lesson.course.title %> Course
        </h2>
      <% end %>
    </div>
  </div>
</header>

app/views/lessons/_lesson_buttons.html.erb
<div class="flex flex-col justify-center max-w-sm mx-auto space-y-6 md:max-w-full md:space-y-0 md:flex-row md:space-x-7">
  <%= link_to path_course_path(course.path, course), class: 'button button--secondary font-medium', data: { test_id: 'view-course-btn' } do %>
    <i class="pr-2 text-lg far fa-map"></i>View Course
  <% end %>

  <% if user_signed_in? %>
    <%= render Complete::ButtonComponent.new(lesson:, current_user:) %>
  <% else %>
    <%= link_to(
          'Sign in to track progress',
          sign_in_path,
          class: 'button button--primary',
          data: { test_id: 'sign_in_button' }
        ) %>
  <% end %>

  <% if lesson.next_lesson %>
    <%= link_to lesson_path(lesson.next_lesson), class: 'button button--secondary font-medium', data: { test_id: 'next-lesson-btn' } do %>
      <i class="pr-2 text-lg far fa-arrow-alt-circle-right" aria-hidden="true"></i>Next Lesson
    <% end %>
  <% elsif lesson.choose_path_lesson? %>
    <%= link_to paths_url, class: 'button button--secondary font-medium', data: { test_id: 'choose-path-lesson-btn' } do %>
      <i class="pr-2 text-lg fas fa-road" aria-hidden="true"></i>Choose Path
    <% end %>
  <% end %>
</div>

app/views/lessons/show.html.erb
<%= title(@lesson.title) %>

<div class="bg-white dark:bg-gray-900">
  <div class="page-container">

    <%= render 'lessons/header', lesson: @lesson %>

    <main class="grid grid-cols-12 gap-x-6" data-controller="lesson-toc" data-lesson-toc-item-classes-value="no-underline hover:text-gray-800 text-sm dark:hover:text-gray-300">
      <article class="col-span-full xl:col-span-7 xl:col-start-2">
        <%= render ContentContainerComponent.new(classes: 'xl:mx-0', data_attributes: { lesson_toc_target: 'lessonContent' }) do %>
          <%= @lesson.body.html_safe %>
        <% end %>
      </article>

      <aside class="col-span-3 col-start-10 justify-self-end hidden xl:block">
        <div class="sticky top-12 pb-20">
          <h4 class="text-md pb-4 text-gray-700 dark:text-gray-300">Lesson contents</h4>
          <ul class="flex flex-col text-gray-500 dark:text-gray-400" data-lesson-toc-target="toc"></ul>
        </div>
      </aside>
    </main>
  </div>
</div>

<div class="bg-gray-100 dark:bg-gray-800/30 text-center">
  <div class="page-container">

    <%= render CardComponent.new do |card| %>
      <% card.body do %>
        <% if user_signed_in? && @lesson.accepts_submission? %>
          <%= react_component(
                'project-submissions/index',
                {
                  userId: current_user.id,
                  course: @lesson.course.as_json,
                  lesson: @lesson.as_json,
                  submissions: @project_submissions,
                  allSubmissionsPath: lesson_project_submissions_path(@lesson.id),
                  userSubmission: @user_submission
                }
              ) %>
        <% elsif @lesson.accepts_submission? %>
          <p class="mb-7">
            Please <%= link_to 'Sign in', sign_in_path, class: 'text-gold' %> or <%= link_to 'Sign up', sign_up_path, class: 'text-gold', data: {test_id: 'sign_up'} %> to view user submissions for this project!
          </p>
        <% end %>

        <%= render 'lesson_buttons', lesson: @lesson, course: @lesson.course, user: @user %>
      <% end %>
    <% end %>

    <div class="pt-10 pb-36">
      <%= link_to github_edit_url(@lesson), target: :_blank, rel: 'noreferrer noopener', class: 'text-gold-600 hover:underline' do %>
        <span class="fab fa-github mr-1"></span>
        Improve this lesson on GitHub
      <% end %>
    </div>

    <%= render 'advert' %>
  </div>
</div>